[package]
name = "umc-carrier-tcp"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
umc-types = { path = "../../crates/umc-types" }
umc-carrier = { path = "../../crates/umc-carrier" }
tokio = { version = "1", features = ["rt", "net", "io-util", "sync"] }

[lints]
workspace = true
