//! Versioned vectors generated by the independent Python `cryptography`
//! implementation (2026-08-10).
//!
//! These values are deliberately literal rather than produced by a Rust
//! helper in the test. They cover the identity, X25519, Initial key schedule,
//! binding-signature, and Finished-MAC boundaries that must remain
//! interoperable.

use umc_crypto::signatures::{IdentityKeyPair, StaticHandshakeKeyPair};
use umc_handshake::identity::{endpoint_id, IdentityBinding};
use umc_handshake::initial::derive_initial_keys;
use umc_handshake::transcript::Transcript;
use umc_handshake::xx::finished_mac;

fn bytes(hex: &str) -> Vec<u8> {
    assert_eq!(hex.len() % 2, 0);
    hex.as_bytes()
        .chunks_exact(2)
        .map(|pair| {
            let high =
                u8::try_from((pair[0] as char).to_digit(16).expect("hex")).expect("hex nibble");
            let low =
                u8::try_from((pair[1] as char).to_digit(16).expect("hex")).expect("hex nibble");
            (high << 4) | low
        })
        .collect()
}

fn array<const N: usize>(hex: &str) -> [u8; N] {
    bytes(hex).try_into().expect("vector length")
}

#[test]
fn independent_identity_and_binding_vectors_match() {
    let identity = IdentityKeyPair::from_seed([
        0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
        25, 26, 27, 28, 29, 30, 31,
    ]);
    assert_eq!(
        identity.public().0.as_slice(),
        bytes("03a107bff3ce10be1d70dd18e74bc09967e4d6309ba50d5f1ddc8664125531b8")
    );
    assert_eq!(
        endpoint_id(&identity.public()),
        array("e502984d2fdd0d0e343b6c01020913ba249bdf34a4e5abd6b26adede67f84418")
    );

    let static_key = StaticHandshakeKeyPair::from_seed([
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63,
    ]);
    assert_eq!(
        static_key.public().0.as_slice(),
        bytes("358072d6365880d1aeea329adf9121383851ed21a28e3b75e965d0d2cd166254")
    );
    let binding = IdentityBinding::sign(&identity, &static_key.public(), 0, u64::MAX, 0, [0; 32]);
    assert_eq!(
        binding.signed_message(),
        array("a840d3367a5593f347ed56bc80c66ba2859f737a6d4772cb315f11c74b3d77ec")
    );
    assert_eq!(
        binding.signature,
        array("cdebd592e5039322a0ab784ef8e71274bd071d05f94f47daa8cb183eb8131b316e64048b383a3998132da2a17af943d4d0f0659e0f9a5a9f4fc092f39951a90c")
    );
    binding
        .validate(u64::MAX / 2, 0)
        .expect("vector binding validates");
}

#[test]
fn independent_x25519_and_initial_key_vectors_match() {
    let static_key = StaticHandshakeKeyPair::from_seed([
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54,
        55, 56, 57, 58, 59, 60, 61, 62, 63,
    ]);
    let peer = StaticHandshakeKeyPair::from_seed([
        64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
        87, 88, 89, 90, 91, 92, 93, 94, 95,
    ]);
    assert_eq!(
        static_key.diffie_hellman(&peer.public()).as_slice(),
        bytes("04c304fb1ca83cee75e206344231f33797e07d9929db670994b7c6fbeb1dc255")
    );

    let keys = derive_initial_keys(&[1, 2, 3, 4, 5, 6, 7, 8]);
    assert_eq!(
        keys.client.key.as_slice(),
        bytes("d433c4a5429ce9f65ce45e70c293f052712e0717500915bf59e52a05ef07cadf")
    );
    assert_eq!(keys.client.iv.as_slice(), bytes("b6cc267f72c8bb4c2486cdb7"));
    assert_eq!(
        keys.client.hp_key.as_slice(),
        bytes("234899b2b2843979c4a32fdfc0dbfe06b3ee4f67f4a27683eeda829170e2347d")
    );
    assert_eq!(
        keys.server.key.as_slice(),
        bytes("80c9b3db7f4f034d7462cf30d624aa518c143b20a39de69908aff716fab0551d")
    );
}

#[test]
fn independent_handshake_transcript_vector_matches() {
    let messages = [
        (
            0u64,
            bytes("0001020304050607"),
            "de900c05a9d8c004d334faf7642c57c5550bc4f112fbad2c4f7eff1bd70fed35",
        ),
        (
            1u64,
            bytes("101112131415161718191a1b1c1d1e1f"),
            "10367d849034070101fbd620dca35fa29abc4195dce4604796e34ea70381c250",
        ),
        (
            2u64,
            bytes("202122232425262728292a2b2c2d2e2f303132333435363738393a3b3c3d3e3f"),
            "ef1749ac735a49f067cba9682556e0bd53cf1c45428bd95a52a323aab45f12e4",
        ),
        (
            3u64,
            bytes("404142434445464748494a4b4c4d4e4f505152535455565758595a5b5c5d5e5f"),
            "f7698e0aadbc2fe2492688cbfb63ed83e42d6607736b7d42568a93aa3678fd2f",
        ),
        (
            4u64,
            bytes("606162636465666768696a6b6c6d6e6f707172737475767778797a7b7c7d7e7f"),
            "4b8374c66bef9eb1f79e95b2e623d83e5fbbfbd9a5c807b08236f385c4a93faa",
        ),
    ];
    let mut transcript = Transcript::new(b"XX", b"UMP-CRYPTO-1", b"ump.tcp/1");
    assert_eq!(
        transcript.hash,
        array("41a93a180624756a6a69c922e9a7759d78454ae35ad70e96b27416d239983c97")
    );
    for (message_type, body, expected_hash) in messages {
        transcript
            .update_message(message_type, &body)
            .expect("transcript update");
        assert_eq!(transcript.hash, array(expected_hash));
    }
}

#[test]
fn independent_finished_mac_vector_matches() {
    let key = [1u8; 32];
    let transcript = [2u8; 32];
    assert_eq!(
        finished_mac(&key, &transcript),
        array("840802a05549b59b3dee05a6591a781c1e5bd57c3976f12c606c5f40ee3d5389")
    );
}
